# Copyright © 2024, SAS Institute Inc., Cary, NC, USA.  All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

name: Deploy Managed Application

on:
  workflow_call:
    inputs:
      viya_solution_name:
        description: 'SAS Solution to deploy'
        required: true
        default: 'SAS Model Risk Management'
        type: string
      aks_cluster_sizing:
        description: 'AKS Cluster Sizing'
        required: true
        default: 'ProdSmall'
        type: string
      viya_order_sas_uri:
        description: 'SAS URI for Viya Order'
        required: true
        type: string
      viya_admin_password:
        description: 'Viya Admin Password'
        required: true
        type: string
      ssh_public_key:
        description: 'SSH Public Key for the deployment'
        required: true
        type: string

      environment:
        description: 'Environment to deploy to'
        required: true
        type: string
        
      additional_parameters:
        description: 'Additional Parameters for the deployment'
        required: false
        type: string
        default: '{}'

  workflow_dispatch:
    inputs:
      viya_solution_name:
        description: 'SAS Solution to deploy'
        required: true
        default: 'SAS Model Risk Management'
        type: choice
        options:
          - 'SAS Model Risk Management'
      aks_cluster_sizing:
        description: 'AKS Cluster Sizing'
        required: true
        default: 'ProdSmall'
        type: choice
        options:
          - 'ProdSmall'
          - 'ProdMedium'
          - 'ProdLarge'
      viya_order_sas_uri:
        description: 'SAS URI for Viya Order'
        required: true
        type: string
      viya_admin_password:
        description: 'Viya Admin Password'
        required: true
        type: string
      ssh_public_key:
        description: 'SSH Public Key for the deployment'
        required: true
        type: string

      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'Azure - RiskCloudInfrastructure-Public Subscription'
        type: choice
        options: 
          - 'Azure - RiskCloudInfrastructure-Public Subscription'
        
      additional_parameters:
        description: 'Additional Parameters for the deployment'
        required: false
        type: string
        default: '{}'
        

jobs:
  parse-additional-parameters:
    uses: ./.github/workflows/parse-additional-parameters.yaml
    with:
      json_input: ${{ inputs.additional_parameters }}
      extracted_keys_with_defaults: |
        {
          "mapp_rg_name": "mapp-${{ github.run_id }}-rg",
          "mapp_def_name": "mappdef-${{ github.run_id }}",
          "update_existing_deployment_mrg_name": "",

          "azure_admin_group_name": "",
          "azure_admin_group_role": "",

          "dns_suffix": "",
          "tls_cert_b64": "",
          "tls_key_b64": "",
          "tls_trusted_ca_certs_b64": "",

          "ext_pg_ids_admin_user": "",
          "ext_pg_ids_admin_password": "",
          "ext_pg_cds_admin_user": "",
          "ext_pg_cds_admin_password": "",

          "location": "eastus",

          "ip_allow_list": "",

          "package_version": "latest",

          "step_add_users": "5",
          "step_install_superset_flag": "N",
          "step_update_spec_cirrus_flag": "N",
          "step_update_spec_cas_flag": "N",
          "step_wait_for_cirrus_flag": "Y",
          "step_disable_cas_flag": "N",
          "step_disable_nonessential_apps_run_time_flag": "N"
        }

  determine-sas-solution:
    uses: ./.github/workflows/determine-sas-solution.yaml
    with:
      viya_solution_name: ${{ inputs.viya_solution_name }}

  call-retrieve-package:
    needs: 
      - parse-additional-parameters
      - determine-sas-solution
    uses: ./.github/workflows/retrieve-package.yaml
    with:
      artifact_name: package-deploy-${{ fromJSON(needs.parse-additional-parameters.outputs.vars).mapp_def_name }}
      package_version: ${{ fromJSON(needs.parse-additional-parameters.outputs.vars).package_version }}
      viya_solution: ${{ needs.determine-sas-solution.outputs.viya_solution }}

#  download-and-upload-package-again:
#    needs: call-retrieve-package
#    uses: ./.github/workflows/download-and-upload-package-again.yaml
#    with:
#      input_package_name: package
#      output_package_name: package2
#      output_package_path: ${{ needs.call-retrieve-package.outputs.artifact_file_name }}

  call-create-storage-account-and-container:
    needs: 
      - call-retrieve-package
#      - download-and-upload-package-again
      - parse-additional-parameters
    secrets: inherit
    uses: ./.github/workflows/create-storage-account-and-container.yaml
    with:
      storage_account_rg: sa-rg
      storage_account_name: viyasolutions  # Storage account name must be between 3 and 24 characters in length and use numbers and lower-case letters only.
      storage_account_container_name: sac-${{github.run_id}}
      location: ${{ fromJSON(needs.parse-additional-parameters.outputs.vars).location }}
      environment: ${{ inputs.environment }}
      artifact_name: package-deploy-${{ fromJSON(needs.parse-additional-parameters.outputs.vars).mapp_def_name }}
      artifact_file_name: ${{ needs.call-retrieve-package.outputs.artifact_file_name }}
#TODO fix artifact name

  call-create-managed-app-definition:
    needs: 
      - parse-additional-parameters
      - call-create-storage-account-and-container
    secrets: inherit
    uses: ./.github/workflows/create-managed-app-definition.yaml
    with:
      environment: ${{ inputs.environment }}
      package_sas_uri: ${{ needs.call-create-storage-account-and-container.outputs.package_sas_uri }}
      mapp_rg_name: ${{ fromJSON(needs.parse-additional-parameters.outputs.vars).mapp_rg_name }}
      mapp_def_name: ${{ fromJSON(needs.parse-additional-parameters.outputs.vars).mapp_def_name }}
      location: ${{ fromJSON(needs.parse-additional-parameters.outputs.vars).location }}
      azure_admin_group_name: ${{ fromJSON(needs.parse-additional-parameters.outputs.vars).azure_admin_group_name }}
      azure_admin_group_role: ${{ fromJSON(needs.parse-additional-parameters.outputs.vars).azure_admin_group_role }}
      
  call-create-managed-app:
    needs: 
      - parse-additional-parameters
      - call-create-managed-app-definition
    secrets: inherit
    uses: ./.github/workflows/create-managed-app.yaml
    with:
      environment: ${{ inputs.environment }}
      mapp_rg_name: ${{ fromJSON(needs.parse-additional-parameters.outputs.vars).mapp_rg_name }}
      mapp_def_name: ${{ fromJSON(needs.parse-additional-parameters.outputs.vars).mapp_def_name }}
      location: ${{ fromJSON(needs.parse-additional-parameters.outputs.vars).location }}
      update_existing_deployment_mrg_name: ${{ fromJSON(needs.parse-additional-parameters.outputs.vars).update_existing_deployment_mrg_name }}
      aks_cluster_sizing: ${{ inputs.aks_cluster_sizing }}
      viya_order_sas_uri: ${{ inputs.viya_order_sas_uri }}
      viya_admin_password: ${{ inputs.viya_admin_password }}
      ssh_public_key: ${{ inputs.ssh_public_key }}
      ip_allow_list: ${{ fromJSON(needs.parse-additional-parameters.outputs.vars).ip_allow_list }}
      step_install_superset_flag: ${{ fromJSON(needs.parse-additional-parameters.outputs.vars).step_install_superset_flag }}
      step_update_spec_cirrus_flag: ${{ fromJSON(needs.parse-additional-parameters.outputs.vars).step_update_spec_cirrus_flag }}
      step_update_spec_cas_flag: ${{ fromJSON(needs.parse-additional-parameters.outputs.vars).step_update_spec_cas_flag }}
      step_wait_for_cirrus_flag: ${{ fromJSON(needs.parse-additional-parameters.outputs.vars).step_wait_for_cirrus_flag }}
      step_add_users: ${{ fromJSON(needs.parse-additional-parameters.outputs.vars).step_add_users }}
      step_disable_cas_flag: ${{ fromJSON(needs.parse-additional-parameters.outputs.vars).step_disable_cas_flag }}
      step_disable_nonessential_apps_run_time_flag: ${{ fromJSON(needs.parse-additional-parameters.outputs.vars).step_disable_nonessential_apps_run_time_flag }}
      dns_suffix: ${{ fromJSON(needs.parse-additional-parameters.outputs.vars).dns_suffix }}
      tls_cert_b64: ${{ fromJSON(needs.parse-additional-parameters.outputs.vars).tls_cert_b64 }}
      tls_key_b64: ${{ fromJSON(needs.parse-additional-parameters.outputs.vars).tls_key_b64 }}
      tls_trusted_ca_certs_b64: ${{ fromJSON(needs.parse-additional-parameters.outputs.vars).tls_trusted_ca_certs_b64 }}
      ext_pg_ids_admin_user: ${{ fromJSON(needs.parse-additional-parameters.outputs.vars).ext_pg_ids_admin_user }}
      ext_pg_ids_admin_password: ${{ fromJSON(needs.parse-additional-parameters.outputs.vars).ext_pg_ids_admin_password }}
      ext_pg_cds_admin_user: ${{ fromJSON(needs.parse-additional-parameters.outputs.vars).ext_pg_cds_admin_user }}
      ext_pg_cds_admin_password: ${{ fromJSON(needs.parse-additional-parameters.outputs.vars).ext_pg_cds_admin_password }}
      
      
      
      