# Copyright © 2024, SAS Institute Inc., Cary, NC, USA.  All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

---
name: (RW) Prepare Monitoring Managed Application
run-name: prepare-monitoring-managed-app

on:
  workflow_call:
    inputs:
      #Required inputs
      environment:
        description: 'The environment the managed application has been deployed to.'
        required: true
        type: string
      mapp_rg_prefix:
        description: 'The prefix for the managed application resource group.'
        required: true
        type: string
      mapp_suffix_id:
        description: 'The suffix ID for the managed application, typically the run ID.'
        required: true
        type: string
      pollInterval:
        description: 'The interval in seconds to poll the managed application status.'
        required: false
        type: string
        default: 30
      timeoutInSecondsDeploymentScripts:
        description: 'The timeout in seconds for the deployment scripts to be created.'
        required: false
        type: string
        default: 900

permissions:
  id-token: write
  contents: read

jobs:
  prepare-monitoring-managed-app:
    name: prepare-monitoring-managed-app
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
      
    steps:
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Wait for Managed Application Deployment
        env: 
          managed_rg: ${{ inputs.mapp_rg_prefix }}-${{ inputs.mapp_suffix_id }}-mrg
          deployment_name: ${{ inputs.mapp_rg_prefix }}-${{ inputs.mapp_suffix_id }}-deploy
          subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          pollInterval: ${{ inputs.pollInterval }}
          timeoutInSecondsDeploymentScripts: ${{ inputs.timeoutInSecondsDeploymentScripts }}
        shell: bash
        run: |
          echo "Wait for a specific deployment resource (${deployment_name}) in ${managed_rg} resource group to exist. This might take a while..."
          az deployment group wait -g ${managed_rg} --name ${deployment_name} --interval $pollInterval --timeout $timeoutInSecondsDeploymentScripts --exists

          echo "Sleep 1 minute before checking the existence of deployment scripts."
          sleep 60

          maxDurationInSeconds=240
          start_datetime=$(date +%s)
          while true
          do
              if [ "$(date +%s)" -gt "$(($start_datetime + ${maxDurationInSeconds}))" ]
              then
                  echo "⏰ Timeout reached"
                  echo "status=TIMEOUT" >> "$GITHUB_OUTPUT"
                  exit 1
              fi

              echo "[$(date)] Checking for deployment scripts in resource group: $managed_rg"
              if ! az deployment-scripts list -g ${managed_rg} --subscription ${subscription_id} > /dev/null
              then
                  echo "Sleep $pollInterval seconds"
                  sleep $pollInterval
              else
                  break
              fi
          done

